#!/bin/sh

#
# Copyright © 2015-2023 Gradle, Inc.
# https://gradle.org
#
# This software is licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
# OF ANY KIND, either express or implied. See the License for the specific
# language governing permissions and limitations under the License.
#

##############################################################################
#
#   IMPORTANT: DO NOT EDIT THIS FILE!
#
#   This file is part of the Gradle Wrapper and is generated by Gradle.
#   Any changes made to this file will be overwritten the next time you run
#   'gradle wrapper' in the root directory.
#
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname -s`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  Nonstop* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

#
# Determine the Java command to use to start the JVM.
#
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/bin/java" ] ; then
        JAVACMD=$JAVA_HOME/bin/java
    else
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."

    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case `uname -r` in
        5.* | 6.* | 7.* ) # Linux
            MAX_FD=65536
            ;;
    esac
    case `uname -s` in
        Linux* )
            ulimit -n $MAX_FD > /dev/null 2>&1
            ;;
    esac
fi

eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"$@\""

# By default, use the UTF-8 character encoding.
SAVE_LC_ALL=$LC_ALL
LC_ALL=en_US.UTF-8
export LC_ALL

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"$@\""

# Setup the command line
CMD_LINE="$JAVACMD $JAVA_OPTS $GRADLE_OPTS -Dorg.gradle.appname=$APP_BASE_NAME -Dfile.encoding=$FILE_ENCODING -classpath \"$CLASSPATH\" org.gradle.wrapper.GradleWrapperMain"

# Execute the command line
save=$-
set -e
exec $CMD_LINE "$@"
